const express = require('express')
const routes = express.Router()
const dashboardController = require('./controllers/DashboardController')
const cepController = require('./controllers/CepController')
const cadastroController = require('./controllers/cadastroController')
const loginController = require('./controllers/loginController')
const carrinhoDeCompraController = require('./controllers/carrinhoDeCompraController')
const notebookController = require('./controllers/notebookController')
const searchController = require('./controllers/searchController')
const camisaController = require('./controllers/camisacontroller')
const avaliacaoController = require('./controllers/avaliacaoController')

routes.get('/',dashboardController.index)
routes.get('/cep',cepController.index)
routes.post('/cep',cepController.verificar)
routes.post('/exit/:id',loginController.exit)
routes.get('/login',loginController.index)
routes.post('/login',loginController.login)
routes.get('/cadastro',cadastroController.index)
routes.post('/cadastro',cadastroController.create)
routes.get('/carrinho-de-compra',carrinhoDeCompraController.index)
routes.get('/notebook',notebookController.index)
routes.get('/camisa',camisaController.produtoShow)
routes.post('/add_produto',carrinhoDeCompraController.add)
routes.post('/del_produto',carrinhoDeCompraController.delete)
routes.post('/view',searchController.view)
routes.get('/departamento-notebook',notebookController.show)
routes.get('/departamento-camisa',camisaController.show)
routes.get('/avaliacao',avaliacaoController.index)
routes.post('/avaliar',avaliacaoController.avaliar)

module.exports = routes